Repository nss-evening-cohort-14/whalom-park-dashboard-whalom-park-dashboard, pull requests merged in 2021-04, with the labels that each got.

#102 Fixed Form Submit Bugs
  src/javascripts/components/forms/eventForms/addEvent.js
  src/javascripts/components/forms/eventForms/editEvent.js
  src/javascripts/components/forms/rideForms/createRideForm.js
  src/javascripts/components/forms/rideForms/editRideForm.js
  src/javascripts/components/forms/staffForms/createStaffForm.js
  src/javascripts/components/forms/staffForms/editStaffForm.js
  src/javascripts/components/forms/vendorForms/editVendorForm.js
  src/javascripts/components/forms/visitorForms/addVisitorForm.js
  src/javascripts/components/forms/visitorForms/editVisitorForm.js
  src/javascripts/events/domEvents.js
Labels: bug

#107 Added templates.
  issue_template.md
  pull_request_template.md
Labels: documentation

#103 Add form bug / Styling Updates
  src/javascripts/components/cards/events.js
  src/javascripts/components/cards/log.js
  src/javascripts/components/cards/rides.js
  src/javascripts/components/cards/staff.js
  src/javascripts/components/cards/vendor.js
  src/javascripts/components/cards/visitors.js
  src/javascripts/components/forms/eventForms/addEvent.js
  src/javascripts/components/forms/rideForms/createRideForm.js
  src/javascripts/components/forms/staffForms/createStaffForm.js
  src/javascripts/components/forms/vendorForms/addVendorForm.js
  src/javascripts/components/forms/visitorForms/addVisitorForm.js
  src/javascripts/components/navBar.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/data/eventData/eventsData.js
  src/javascripts/helpers/data/ownerInfo/ownerInfo.js
  src/javascripts/helpers/data/vendorData/vendorData.js
  src/styles/main.scss
Labels: bug, enhancement

#111 added assignment ID to json sample file
  json_sample_data/staff.json
Labels: documentation

#113 Hide performance
  src/javascripts/components/navBar.js
Labels: bug, enhancement

#112 Week2 Setup
  README.md
  issue_template.md
  json_sample_data/logWeek2.json
  json_sample_data/ridesWeek2.json
  json_sample_data/staff.json
  json_sample_data/vendorsWeek2.json
  package.json
  pull_request_template.md
  src/javascripts/components/cards/events.js
  src/javascripts/components/cards/log.js
  src/javascripts/components/cards/rides.js
  src/javascripts/components/cards/staff.js
  src/javascripts/components/cards/vendor.js
  src/javascripts/components/cards/visitors.js
  src/javascripts/components/forms/eventForms/addEvent.js
  src/javascripts/components/forms/eventForms/editEvent.js
  src/javascripts/components/forms/rideForms/createRideForm.js
  src/javascripts/components/forms/rideForms/editRideForm.js
  src/javascripts/components/forms/staffForms/createStaffForm.js
  src/javascripts/components/forms/staffForms/editStaffForm.js
  src/javascripts/components/forms/vendorForms/addVendorForm.js
  src/javascripts/components/forms/vendorForms/editVendorForm.js
  src/javascripts/components/forms/visitorForms/addVisitorForm.js
  src/javascripts/components/forms/visitorForms/editVisitorForm.js
  src/javascripts/components/navBar.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/auth/router.js
  src/javascripts/helpers/auth/signOut.js
  src/javascripts/helpers/data/eventData/eventsData.js
  src/javascripts/helpers/data/ownerInfo/ownerInfo.js
  src/javascripts/helpers/data/rideData/ridesData.js
  src/javascripts/helpers/data/staffData/staffData.js
  src/javascripts/helpers/data/vendorData/vendorData.js
  src/javascripts/helpers/data/visitorData/visitorsData.js
  src/styles/main.scss
Labels: bug, enhancement

#114 Income Pie Chart
  package.json
  src/javascripts/components/cards/log.js
  src/javascripts/helpers/data/logData.js
  src/javascripts/helpers/incomeChart.js
  src/styles/main.scss
Labels: enhancement

#115 Mg charging visitors
  package.json
  src/javascripts/components/cards/events.js
  src/javascripts/components/cards/log.js
  src/javascripts/components/cards/rides.js
  src/javascripts/components/cards/staff.js
  src/javascripts/components/cards/vendor.js
  src/javascripts/components/cards/visitors.js
  src/javascripts/components/domBuilder.js
  src/javascripts/events/domEvents.js
  src/javascripts/helpers/data/logData.js
Labels: enhancement
